using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Shares.Enum
{
    public enum HorseFur
    {
        Alle,
        Apfelschimmel,
        ApfelschimmelTobianoScheckung,
        Braun,
        Brauner,
        BraunerLeopard,
        BraunerOveroScheckung,
        BraunerTobianoScheckung,
        BraunerToveroScheckung,
        Braunfalben,
        Braunschecke,
        Cremello,
        CremelloTobianoScheckung,
        Dunkelbrauner,
        DunkelbraunerOveroScheckung,
        DunkelbraunerTobianoScheckung,
        DunkelbraunerToveroScheckung,
        Dunkelfuchs,
        DunkelfuchsOveroScheckung,
        DunkelfuchsTobianoScheckung,
        DunkelfuchsToveroScheckung,
        DunkelfuchshellerMähne,
        Dunkelfuchsschecke,
        FalbSchecke,
        Falbe,
        FalbeOveroScheckung,
        FalbeTobianoScheckung,
        Forellenschimmel,
        Fuchs,
        FuchsTobianoScheckung,
        FuchsToveroScheckung,
        FuchshellerMähne,
        Fuchsschecke,
        Gelbfalben,
        Graufalben,
        Hellfalben,
        Hellgrau,
        LeichtgefleckterBrauner,
        LeichtgefleckterRotfuchs,
        Mausgrau,
        MausgrauerTobianoScheckung,
        OveroFuchsschecke,
        Palomino,
        PalominoOveroScheckung,
        PalominoTobianoScheckung,
        PalominoToveroScheckung,
        PalominoSchecke,
        Rappe,
        RappeOveroScheckung,
        RappeTobianoScheckung,
        RappeToveroScheckung,
        Rappschecke,
        Roan,
        Rotbrauner,
        RotbraunerOveroScheckung,
        RotbraunerTobianoScheckung,
        Rotfalben,
        Rotschecke,
        SchabrackenFalbe,
        Schabrackenbrauner,
        Schabrackendunkelfuchs,
        Schabrackenfuchs,
        Schabrackenpalomino,
        Schabrackenrappe,
        Schabrackenrotbrauner,
        Schimmel,
        StrawberryRoan,
        WenigeschwarzeFlecken,
        BrauneSchneeflocke,
        FuchsfarbeneSchneeflocke,
        FuchsfarbenerLeopard,
        SchwarzeSchneeflocke,
        SchwarzerLeopard
    }
}
